# Deploy .NET 6 Console App as EXE

FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM base as final
#WORKDIR /app
COPY /bin/Debug/net6.0 .
#ENTRYPOINT ["ConsoleApp2.exe"]
ENTRYPOINT ["dotnet", "ConsoleApp2.dll"]